In [ ]:
import pandas as pd
import numpy as np
np.set_printoptions(suppress=True, linewidth=160)


In [ ]:
df = pd.read_csv('./data/data.csv')

In [ ]:
df

842302  M  17.99  10.38   122.8    1001   0.1184   0.2776   0.3001  \
0      842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
1    84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
2    84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
3    84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
4      843786  M  12.45  15.70   82.57   477.1  0.12780  0.17000  0.15780   
..        ... ..    ...    ...     ...     ...      ...      ...      ...   
563    926424  M  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
564    926682  M  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
565    926954  M  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
566    927241  M  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
567     92751  B   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

      0.1471  ...   25.38  17.33   184.6    2019   0.1622   0.6656  0.7119  \
0    0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
1    0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
2    0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
3    0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
4    0.08089  ...  15.470  23.75  103.40   741.6  0.17910  0.52490  0.5355   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
563  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
564  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
565  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
566  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
567  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

     0.2654  0.4601   0.1189  
0    0.1860  0.2750  0.08902  
1    0.2430  0.3613  0.08758  
2    0.2575  0.6638  0.17300  
3    0.1625  0.2364  0.07678  
4    0.1741  0.3985  0.12440  
..      ...     ...      ...  
563  0.2216  0.2060  0.07115  
564  0.1628  0.2572  0.06637  
565  0.1418  0.2218  0.07820  
566  0.2650  0.4087  0.12400  
567  0.0000  0.2871  0.07039  

[568 rows x 32 columns]

In [ ]:
# Extract features (X) by selecting all columns except the label column
X = df.iloc[:, 2:]
X

17.99  10.38   122.8    1001   0.1184   0.2776   0.3001   0.1471  0.2419  \
0    20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017  0.1812   
1    19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790  0.2069   
2    11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520  0.2597   
3    20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430  0.1809   
4    12.45  15.70   82.57   477.1  0.12780  0.17000  0.15780  0.08089  0.2087   
..     ...    ...     ...     ...      ...      ...      ...      ...     ...   
563  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390  0.13890  0.1726   
564  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791  0.1752   
565  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302  0.1590   
566  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200  0.2397   
567   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000  0.1587   

     0.07871  ...   25.38  17.33   184.6    2019   0.1622   0.6656  0.7119  \
0    0.05667  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
1    0.05999  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
2    0.09744  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
3    0.05883  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
4    0.07613  ...  15.470  23.75  103.40   741.6  0.17910  0.52490  0.5355   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
563  0.05623  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
564  0.05533  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
565  0.05648  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
566  0.07016  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
567  0.05884  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

     0.2654  0.4601   0.1189  
0    0.1860  0.2750  0.08902  
1    0.2430  0.3613  0.08758  
2    0.2575  0.6638  0.17300  
3    0.1625  0.2364  0.07678  
4    0.1741  0.3985  0.12440  
..      ...     ...      ...  
563  0.2216  0.2060  0.07115  
564  0.1628  0.2572  0.06637  
565  0.1418  0.2218  0.07820  
566  0.2650  0.4087  0.12400  
567  0.0000  0.2871  0.07039  

[568 rows x 30 columns]

In [ ]:
X = X.values
X, X.shape

(array([[ 20.57   ,  17.77   , 132.9    , ...,   0.186  ,   0.275  ,   0.08902],
        [ 19.69   ,  21.25   , 130.     , ...,   0.243  ,   0.3613 ,   0.08758],
        [ 11.42   ,  20.38   ,  77.58   , ...,   0.2575 ,   0.6638 ,   0.173  ],
        ...,
        [ 16.6    ,  28.08   , 108.3    , ...,   0.1418 ,   0.2218 ,   0.0782 ],
        [ 20.6    ,  29.33   , 140.1    , ...,   0.265  ,   0.4087 ,   0.124  ],
        [  7.76   ,  24.54   ,  47.92   , ...,   0.     ,   0.2871 ,   0.07039]]),
 (568, 30))

In [ ]:
# Extract labels (y) by selecting only the label column
y = df.iloc[:, 1].values
y, y.shape

(array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
        'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B',
        'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'B',
        'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B',
        'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
        'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M',
        'M', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B',

In [ ]:
# Convert label values to numeric format, e.g., 0 for 'B' and 1 for 'M'
y = np.where(y == 'M', 1, 0)
y, y.shape

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
        1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
X.shape, y.shape

((568, 30), (568,))

In [ ]:
# Define the split ratio
split_ratio = 0.8
split_ratio * len(X), len(X) - (split_ratio * len(X))

(454.40000000000003, 113.59999999999997)

In [ ]:
# Calculate the split index
split_index = int(split_ratio * len(X))
# Split the array into training and validation sets
train_data = X[:split_index]
valid_data = X[split_index:]

In [ ]:
len(train_data), len(valid_data)

(454, 114)

In [ ]:
print(f"Training data: {train_data}")

Training data: [[ 20.57     17.77    132.9     ...   0.186     0.275     0.08902]
 [ 19.69     21.25    130.      ...   0.243     0.3613    0.08758]
 [ 11.42     20.38     77.58    ...   0.2575    0.6638    0.173  ]
 ...
 [ 12.       28.23     76.77    ...   0.07116   0.2447    0.08194]
 [ 14.53     13.98     93.86    ...   0.1069    0.2606    0.0781 ]
 [ 12.62     17.15     80.62    ...   0.09851   0.327     0.0733 ]]


In [ ]:
print(f"Validation data: {valid_data}")

Validation data: [[ 13.38     30.72     86.34    ...   0.07763   0.2196    0.07675]
 [ 11.63     29.29     74.87    ...   0.06835   0.2884    0.0722 ]
 [ 13.21     25.25     84.1     ...   0.06005   0.2444    0.06788]
 ...
 [ 16.6      28.08    108.3     ...   0.1418    0.2218    0.0782 ]
 [ 20.6      29.33    140.1     ...   0.265     0.4087    0.124  ]
 [  7.76     24.54     47.92    ...   0.        0.2871    0.07039]]


## Define the split function

In [ ]:
def data_split(file_path):
    df = pd.read_csv(file_path)
    X = df.iloc[:, 2:]
    y = df.iloc[:, 1].values
    y = np.where(y == 'M', 1, 0)
    
    split_ratio = 0.8
    split_index = int(split_ratio * len(X))
    X_tr, y_tr = X[:split_index], y[:split_index]
    X_val, y_val = X[split_index:], y[split_index:]
    return X_tr, y_tr, X_val, y_val

In [ ]:
X_tr, y_tr, X_val, y_val = data_split('./data/data.csv')

In [ ]:
X_tr.shape, y_tr.shape

((454, 30), (454,))

In [ ]:
X_val.shape, y_val.shape

((114, 30), (114,))