In [ ]:
import numpy as np
from math import *

# Exercise 00

In [ ]:
def sigmoid_(x):
    """
    Compute the sigmoid of a vector.
    Args:
    x: has to be a numpy.ndarray of shape (m, 1).
    Returns:
    The sigmoid value as a numpy.ndarray of shape (m, 1).
    None if x is an empty numpy.ndarray.
    Raises:
    This function should not raise any Exception.
    """

    return 1 / (1 + np.exp(-x))

In [ ]:
# Example 1:
x = np.array([[-4]])
sigmoid_(x)
# Output: array([[0.01798620996209156]])

array([[0.01798621]])

In [ ]:
# Example 2:
x = np.array([[2]])
sigmoid_(x)
# Output: array([[0.8807970779778823]])

array([[0.88079708]])

In [ ]:
# Example 3:
x = np.array([[-4], [2], [0]])
sigmoid_(x)
# Output: array([[0.01798620996209156], [0.8807970779778823], [0.5]])

array([[0.01798621],
       [0.88079708],
       [0.5       ]])

# Exercise 01

In [ ]:
def logistic_predict_(x, theta):
    """
    Computes the vector of prediction y_hat from two non-empty numpy.ndarray.
    
    Args:
    x: has to be an numpy.ndarray, a vector of dimension m * n.
    theta: has to be an numpy.ndarray, a vector of dimension (n + 1) * 1.
    
    Returns:
    y_hat as a numpy.ndarray, a vector of dimension m * 1.
    None if x or theta are empty numpy.ndarray.
    None if x or theta dimensions are not appropriate.
    
    Raises:
    This function should not raise any Exception.
    """
    m,n = x.shape
    x_bias = np.c_[np.ones((m, 1)), x]
    return sigmoid_(np.dot(x_bias, theta))

In [ ]:
# Example 1
x = np.array([4]).reshape((-1, 1))
theta = np.array([[2], [0.5]])
logistic_predict_(x, theta)
# Output: array([[0.98201379]])


array([[0.98201379]])

In [ ]:
# Example 1
x2 = np.array([[4], [7.16], [3.2], [9.37], [0.56]])
theta2 = np.array([[2], [0.5]])
logistic_predict_(x2, theta2)
# Output: array([[0.98201379], [0.99624161], [0.97340301], [0.99875204], [0.90720705]])

array([[0.98201379],
       [0.99624161],
       [0.97340301],
       [0.99875204],
       [0.90720705]])

In [ ]:
# Example 3
x3 = np.array([[0, 2, 3, 4], [2, 4, 5, 5], [1, 3, 2, 7]])
theta3 = np.array([[-2.4], [-1.5], [0.3], [-1.4], [0.7]])
logistic_predict_(x3, theta3)
# Output: array([[0.03916572],[0.00045262],[0.2890505 ]])

array([[0.03916572],
       [0.00045262],
       [0.2890505 ]])

# Exercise 02

In [ ]:
def log_loss_(y, y_hat, eps=1e-15):
    """
    Computes the logistic loss value.
    Args:
    y: has to be an numpy.ndarray, a vector of shape m * 1.
    y_hat: has to be an numpy.ndarray, a vector of shape m * 1.
    eps: has to be a float, epsilon (default=1e-15)
    Returns:
    The logistic loss value as a float.
    None on any error.
    Raises:
    This function should not raise any Exception.
    """

    # y_hat = np.clip(y_hat, eps, 1 - eps)
    # loss = 0.0
    # y, y_hat = y[:, 0], y_hat[:, 0]
    # for i in range(len(y)):
    #     loss -= y[i] * np.log(y_hat[i]) + (1 - y[i]) * np.log(1 - y_hat[i])
    # return (1/x.shape[0]) * loss
    m = y.shape[0]
    y_hat = np.clip(y_hat, eps, 1 - eps)

    loss_value = -1/m * np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))
    return loss_value

In [ ]:
# Example 1:
y1 = np.array([1]).reshape((-1, 1))
x1 = np.array([4]).reshape((-1, 1))
theta1 = np.array([[2], [0.5]])
y_hat1 = logistic_predict_(x1, theta1)
log_loss_(y1, y_hat1)
# Output: 0.01814992791780973

0.01814992791780973

In [ ]:
# Example 2:
y2 = np.array([[1], [0], [1], [0], [1]])
x2 = np.array([[4], [7.16], [3.2], [9.37], [0.56]])
theta2 = np.array([[2], [0.5]])
y_hat2 = logistic_predict_(x2, theta2)
log_loss_(y2, y_hat2)
# Output: 2.4825011602474483

2.4825011602474483

In [ ]:
# Example 3:
y3 = np.array([[0], [1], [1]])
x3 = np.array([[0, 2, 3, 4], [2, 4, 5, 5], [1, 3, 2, 7]])
theta3 = np.array([[-2.4], [-1.5], [0.3], [-1.4], [0.7]])
y_hat3 = logistic_predict_(x3, theta3)
log_loss_(y3, y_hat3)
# Output: 2.9938533108607053

2.9938533108607057

# Exercise 03

In [ ]:
def vec_log_loss_(y, y_hat, eps=1e-15):
    """
    Computes the logistic loss value.
    Args:
    y: has to be an numpy.ndarray, a vector of shape m * 1.
    y_hat: has to be an numpy.ndarray, a vector of shape m * 1.
    eps: has to be a float, epsilon (default=1e-15)
    Returns:
    The logistic loss value as a float.
    None on any error.
    Raises:
    This function should not raise any Exception.
    """

    # y_hat = np.clip(y_hat, eps, 1 - eps)
    # loss = 0.0
    # y, y_hat = y[:, 0], y_hat[:, 0]
    # for i in range(len(y)):
    #     loss -= y[i] * np.log(y_hat[i]) + (1 - y[i]) * np.log(1 - y_hat[i])
    # return (1/x.shape[0]) * loss
    m = y.shape[0]
    y_hat = np.clip(y_hat, eps, 1 - eps)

    loss_value = -1/m * np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))
    return loss_value

In [ ]:
# Example 1:
y1 = np.array([1]).reshape((-1, 1))
x1 = np.array([4]).reshape((-1, 1))
theta1 = np.array([[2], [0.5]])
y_hat1 = logistic_predict_(x1, theta1)
vec_log_loss_(y1, y_hat1)
# Output: 0.01814992791780973

0.01814992791780973

In [ ]:
# Example 2:
y2 = np.array([[1], [0], [1], [0], [1]])
x2 = np.array([[4], [7.16], [3.2], [9.37], [0.56]])
theta2 = np.array([[2], [0.5]])
y_hat2 = logistic_predict_(x2, theta2)
vec_log_loss_(y2, y_hat2)
# Output: 2.4825011602474483

2.4825011602474483

In [ ]:
# Example 3:
y3 = np.array([[0], [1], [1]])
x3 = np.array([[0, 2, 3, 4], [2, 4, 5, 5], [1, 3, 2, 7]])
theta3 = np.array([[-2.4], [-1.5], [0.3], [-1.4], [0.7]])
y_hat3 = logistic_predict_(x3, theta3)
vec_log_loss_(y3, y_hat3)
# Output: 2.9938533108607053

2.9938533108607057

# Exercise 04

In [ ]:
def log_gradient(x, y, theta):
    """
    Computes a gradient vector from three non-empty numpy.ndarray, with a for-loop. The three arrays must have compatiblArgs:
    x: has to be an numpy.ndarray, a matrix of shape m * n.
    y: has to be an numpy.ndarray, a vector of shape m * 1.
    theta: has to be an numpy.ndarray, a vector of shape (n + 1) * 1.
    
    Returns:
    The gradient as a numpy.ndarray, a vector of shape n * 1, containing the result of the formula for all j.
    None if x, y, or theta are empty numpy.ndarray.
    None if x, y and theta do not have compatible dimensions.
    
    Raises:
    This function should not raise any Exception.
    """

    m,n = x.shape
    y_hat = logistic_predict_(x, theta)
    grad = np.zeros((n + 1, 1))

    for i in range(m):
        grad[0] += y_hat[i] - y[i]
        for j in range(1, n + 1):
            grad[j] += (y_hat[i] - y[i]) * x[i, j - 1]

    return grad / m

In [ ]:
# Example 1:
y1 = np.array([1]).reshape((-1, 1))
x1 = np.array([4]).reshape((-1, 1))
theta1 = np.array([[2], [0.5]])
log_gradient(x1, y1, theta1)
# Output: array([[-0.01798621], [-0.07194484]])

array([[-0.01798621],
       [-0.07194484]])

In [ ]:
# Example 2:
y2 = np.array([[1], [0], [1], [0], [1]])
x2 = np.array([[4], [7.16], [3.2], [9.37], [0.56]])
theta2 = np.array([[2], [0.5]])
log_gradient(x2, y2, theta2)
# Output: array([[0.3715235 ], [3.25647547]])

array([[0.3715235 ],
       [3.25647547]])

In [ ]:
# Example 3:
y3 = np.array([[0], [1], [1]])
x3 = np.array([[0, 2, 3, 4], [2, 4, 5, 5], [1, 3, 2, 7]])
theta3 = np.array([[-2.4], [-1.5], [0.3], [-1.4], [0.7]])
log_gradient(x3, y3, theta3)
# Output: array([[-0.55711039], [-0.90334809], [-2.01756886], [-2.10071291], [-3.27257351]])

array([[-0.55711039],
       [-0.90334809],
       [-2.01756886],
       [-2.10071291],
       [-3.27257351]])

# Exercise 05 : 

In [ ]:
def vec_log_gradient(x, y, theta):
    """
    Computes a gradient vector from three non-empty numpy.ndarray, without any for-loop. The three arrays must have compArgs:
    x: has to be an numpy.ndarray, a matrix of shape m * n.
    y: has to be an numpy.ndarray, a vector of shape m * 1.
    theta: has to be an numpy.ndarray, a vector (n +1) * 1.
    
    Returns:
    The gradient as a numpy.ndarray, a vector of shape n * 1, containg the result of the formula for all j.
    None if x, y, or theta are empty numpy.ndarray.
    None if x, y and theta do not have compatible shapes.
    
    Raises:
    This function should not raise any Exception.
    """

    m, n = x.shape
    X = np.c_[np.ones((m, 1)), x]
    return 1/m * X.T@(logistic_predict_(x, theta) - y)

In [ ]:
# Example 1:
y1 = np.array([1]).reshape((-1, 1))
x1 = np.array([4]).reshape((-1, 1))
theta1 = np.array([[2], [0.5]])
vec_log_gradient(x1, y1, theta1)
# Output: array([[-0.01798621], [-0.07194484]])

array([[-0.01798621],
       [-0.07194484]])

In [ ]:
# Example 2:
y2 = np.array([[1], [0], [1], [0], [1]])
x2 = np.array([[4], [7.16], [3.2], [9.37], [0.56]])
theta2 = np.array([[2], [0.5]])
log_gradient(x2, y2, theta2)
# Output: array([[0.3715235 ], [3.25647547]])

array([[0.3715235 ],
       [3.25647547]])

In [ ]:
# Example 3:
y3 = np.array([[0], [1], [1]])
x3 = np.array([[0, 2, 3, 4], [2, 4, 5, 5], [1, 3, 2, 7]])
theta3 = np.array([[-2.4], [-1.5], [0.3], [-1.4], [0.7]])
log_gradient(x3, y3, theta3)
# Output: array([[-0.55711039], [-0.90334809], [-2.01756886], [-2.10071291], [-3.27257351]])

array([[-0.55711039],
       [-0.90334809],
       [-2.01756886],
       [-2.10071291],
       [-3.27257351]])

# Exercise 06 : 

In [ ]:
class MyLogisticRegression():
    """
    Description:
    My personnal logistic regression to classify things.
    """
    
    def __init__(self, theta, alpha=0.001, max_iter=1000):
        self.alpha = alpha
        self.max_iter = max_iter
        self.theta = theta


    def predict_(self, x):
        
        def sigmoid_(x): return 1 / (1 + np.exp(-x))
        
        m,n = x.shape
        x_bias = np.c_[np.ones((m, 1)), x]
        return sigmoid_(np.dot(x_bias, self.theta))
        
    def loss_elem_(self, y, yhat):
        m = y.shape[0]
        eps = 1e-15
        y_hat = np.clip(yhat, eps, 1 - eps)

        return y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat)


    def loss_(self, X, y):
        y_hat = self.predict_(X)
        eps = 1e-15
        m = y.shape[0]
        y_hat = np.clip(y_hat, eps, 1 - eps)

        loss_value = -1/m * np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))
        return loss_value
    
    
    def fit_(self, x, y):
        
        def vec_log_gradient(x, y, theta):
            m, n = x.shape
            X = np.c_[np.ones((m, 1)), x]
            return 1/m * X.T@(self.predict_(x) - y)
        
        for i in range(self.max_iter):
            grad = vec_log_gradient(x, y, self.theta)
            self.theta -= grad * self.alpha
        return self.theta

In [ ]:
import numpy as np
# from my_logistic_regression import MyLogisticRegression as MyLR
X = np.array([[1., 1., 2., 3.], [5., 8., 13., 21.], [3., 5., 9., 14.]])
Y = np.array([[1], [0], [1]])
thetas = np.array([[2], [0.5], [7.1], [-4.3], [2.09]])
mylr = MyLogisticRegression(thetas)
# Example 0:
mylr.predict_(X)
# Output: array([[0.99930437], [1. ], [1. ]])

array([[0.99930437],
       [1.        ],
       [1.        ]])

In [ ]:
# Example 1:
mylr.loss_(X,Y)
# Output: 11.513157421577004

11.513423954053735

In [ ]:
# Example 2:
mylr.fit_(X, Y)
mylr.theta
# Output: array([[ 2.11826435] [ 0.10154334] [ 6.43942899] [-5.10817488] [ 0.6212541 ]])

array([[ 2.11826435],
       [ 0.10154334],
       [ 6.43942899],
       [-5.10817488],
       [ 0.6212541 ]])

In [ ]:
# Example 3:
mylr.predict_(X)
# Output: array([[0.57606717] [0.68599807] [0.06562156]])

array([[0.57606717],
       [0.68599807],
       [0.06562156]])

In [ ]:
# Example 4:
mylr.loss_(X,Y)
# Output: 1.4779126923052268

1.4779126923052321

# Exercise 08 : 

In [ ]:
from sklearn.metrics import *

In [ ]:
def accuracy_score_(y, y_hat):
    """
    Compute the accuracy score.
    Args:
    y:a numpy.ndarray for the correct labels
    y_hat:a numpy.ndarray for the predicted labels
    Returns:
    The accuracy score as a float.
    None on any error.
    Raises:
    This function should not raise any Exception.
    """

    correct_predictions = np.sum(y == y_hat)
    total_predictions = y.size
    
    return correct_predictions / total_predictions
    
    
def precision_score_(y, y_hat, pos_label=1):
    """
    Compute the precision score.
    Args:
    y:a numpy.ndarray for the correct labels
    y_hat:a numpy.ndarray for the predicted labels
    pos_label: str or int, the class on which to report the precision_score (default=1)
    Return:
    The precision score as a float.
    None on any error.
    Raises:
    This function should not raise any Exception.
    """
    tp = np.sum((y == pos_label) & (y_hat == pos_label))
    fp = np.sum((y != pos_label) & (y_hat == pos_label))
    return tp / (tp + fp)

def recall_score_(y, y_hat, pos_label=1):
    """
    Compute the recall score.
    Args:
    y:a numpy.ndarray for the correct labels
    y_hat:a numpy.ndarray for the predicted labels
    pos_label: str or int, the class on which to report the precision_score (default=1)
    Return:
    The recall score as a float.
    None on any error.
    Raises:
    This function should not raise any Exception.
    """

    tp = np.sum((y == pos_label) & (y_hat == pos_label))
    fn = np.sum((y == pos_label) & (y_hat != pos_label))
    return tp / (tp + fn)
    
def f1_score_(y, y_hat, pos_label=1):
    """
    Compute the f1 score.
    Args:
    y:a numpy.ndarray for the correct labels
    y_hat:a numpy.ndarray for the predicted labels
    pos_label: str or int, the class on which to report the precision_score (default=1)
    Returns:
    The f1 score as a float.
    None on any error.
    Raises:
    This function should not raise any Exception.
    """
    precision, recall = precision_score_(y, y_hat, pos_label), recall_score_(y, y_hat, pos_label)
    return (2 * precision * recall) / (precision + recall) 

### Accuracy


In [ ]:
y_hat = np.array([1, 1, 0, 1, 0, 0, 1, 1]).reshape((-1, 1))
y = np.array([1, 0, 0, 1, 0, 1, 0, 0]).reshape((-1, 1))
## your implementation
my_ = accuracy_score_(y, y_hat)
## Output: 0.5
## sklearn implementation
sk_ = accuracy_score(y, y_hat)
## Output: 0.5

In [ ]:
my_, sk_

(0.5, 0.5)

### Precision

In [ ]:
## your implementation
my_ = precision_score_(y, y_hat)
## Output: 0.4
## sklearn implementation
sk_ = precision_score(y, y_hat)
## Output: 0.4

In [ ]:
my_, sk_

(0.4, 0.4)

### Recall


In [ ]:
## your implementation
my_ = recall_score_(y, y_hat)
## Output: 0.6666666666666666
## sklearn implementation
sk_ = recall_score(y, y_hat)
## Output: 0.6666666666666666

In [ ]:
my_, sk_

(0.6666666666666666, 0.6666666666666666)

### F1-score

In [ ]:
## your implementation
my_ = f1_score_(y, y_hat)
## Output: 0.5
## sklearn implementation
sk_ = f1_score(y, y_hat)
## Output: 0.5

In [ ]:
my_, sk_

(0.5, 0.5)

In [ ]:
# Example 2:
y_hat = np.array(['norminet', 'dog', 'norminet', 'norminet', 'dog', 'dog', 'dog', 'dog'])
y = np.array(['dog', 'dog', 'norminet', 'norminet', 'dog', 'norminet', 'dog', 'norminet'])
# Accuracy
## your implementation
assert accuracy_score_(y, y_hat) == accuracy_score(y, y_hat)
assert precision_score_(y, y_hat, pos_label='dog') == precision_score(y, y_hat, pos_label='dog')
assert recall_score_(y, y_hat, pos_label='dog') == recall_score(y, y_hat, pos_label='dog')
assert f1_score_(y, y_hat, pos_label='dog') == f1_score(y, y_hat, pos_label='dog')

In [ ]:
# Example 3:
y_hat = np.array(['norminet', 'dog', 'norminet', 'norminet', 'dog', 'dog', 'dog', 'dog'])
y = np.array(['dog', 'dog', 'norminet', 'norminet', 'dog', 'norminet', 'dog', 'norminet'])
assert precision_score_(y, y_hat, pos_label='norminet') == precision_score(y, y_hat, pos_label='norminet')
assert recall_score_(y, y_hat, pos_label='norminet') == recall_score(y, y_hat, pos_label='norminet')
assert f1_score_(y, y_hat, pos_label='norminet') == f1_score(y, y_hat, pos_label='norminet')

# Exercise 09

In [ ]:
def confusion_matrix_(y_true, y_hat, labels=None):
    """
    Compute confusion matrix to evaluate the accuracy of a classification.
    Args:
    y:a numpy.array for the correct labels
    y_hat:a numpy.array for the predicted labels
    labels: optional, a list of labels to index the matrix.
    This may be used to reorder or select a subset of labels. (default=None)
    df_option: optional, if set to True the function will return a pandas DataFrame
    instead of a numpy array. (default=False)
    Return:
    The confusion matrix as a numpy array or a pandas DataFrame according to df_option value.
    None if any error.
    Raises:
    This function should not raise any Exception.
    """
    
    if labels is None:
        labels = np.unique(np.concatenate((y_true, y_hat)))

    matrix = np.zeros((len(labels), len(labels)))

    for i, label1 in enumerate(labels):
        for j, label2 in enumerate(labels):
            matrix[i, j] = np.sum((y_true == label1) & (y_hat == label2))

    return matrix


In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix
y_hat = np.array([['norminet'], ['dog'], ['norminet'], ['norminet'], ['dog'], ['bird']])
y = np.array([['dog'], ['dog'], ['norminet'], ['norminet'], ['dog'], ['norminet']])

confusion_matrix_(y, y_hat)
## Output:
# array([[0 0 0]
# [0 2 1]
# [1 0 2]])

array([[0., 0., 0.],
       [0., 2., 1.],
       [1., 0., 2.]])

In [ ]:
## sklearn implementation
confusion_matrix(y, y_hat)
## Output:
# array([[0 0 0]
# [0 2 1]
# [1 0 2]])

array([[0, 0, 0],
       [0, 2, 1],
       [1, 0, 2]])

In [ ]:
# Example 2:
## your implementation
confusion_matrix_(y, y_hat, labels=['dog', 'norminet'])
## Output:
# array([[2 1]
# [0 2]])

array([[2., 1.],
       [0., 2.]])

In [ ]:
## sklearn implementation
confusion_matrix(y, y_hat, labels=['dog', 'norminet'])
## Output:
# array([[2 1]
# [0 2]])

array([[2, 1],
       [0, 2]])