In [ ]:
import numpy as np
from math import *

# Exercise 00

In [ ]:
def add_polynomial_features(x, power):
    """
    Add polynomial features to matrix x by raising its columns to every power in the range of 1 up to the power giveArgs:
    x: has to be an numpy.ndarray, a matrix of shape m * n.
    power: has to be an int, the power up to which the columns of matrix x are going to be raised.
    
    Returns:
    The matrix of polynomial features as a numpy.ndarray, of shape m * (np), containg the polynomial feature vaNone if x is an empty numpy.ndarray.
    
    Raises:
    This function should not raise any Exception.
    """

    out = [x]
    for i in range(2, power+1):
        out.append(x ** i)
    return np.hstack(out)

In [ ]:
x = np.arange(1,11).reshape(5, 2)

In [ ]:
add_polynomial_features(x, 3)
# Output:
# array([[ 1, 2, 1, 4, 1, 8],
# [ 3, 4, 9, 16, 27, 64],
# [ 5, 6, 25, 36, 125, 216],
# [ 7, 8, 49, 64, 343, 512],
# [ 9, 10, 81, 100, 729, 1000]])

array([[   1,    2,    1,    4,    1,    8],
       [   3,    4,    9,   16,   27,   64],
       [   5,    6,   25,   36,  125,  216],
       [   7,    8,   49,   64,  343,  512],
       [   9,   10,   81,  100,  729, 1000]])

In [ ]:
add_polynomial_features(x, 4)
# Output:
# array([[ 1, 2, 1, 4, 1, 8, 1, 16],
# [ 3, 4, 9, 16, 27, 64, 81, 256],
# [ 5, 6, 25, 36, 125, 216, 625, 1296],
# [ 7, 8, 49, 64, 343, 512, 2401, 4096],
# [ 9, 10, 81, 100, 729, 1000, 6561, 10000]])

array([[    1,     2,     1,     4,     1,     8,     1,    16],
       [    3,     4,     9,    16,    27,    64,    81,   256],
       [    5,     6,    25,    36,   125,   216,   625,  1296],
       [    7,     8,    49,    64,   343,   512,  2401,  4096],
       [    9,    10,    81,   100,   729,  1000,  6561, 10000]])

# Exercise 01

In [ ]:
def iterative_l2(theta):
    """
    Computes the L2 regularization of a non-empty numpy.ndarray, with a for-loop.
    
    Args:
    theta: has to be a numpy.ndarray, a vector of shape n * 1.
    
    Returns:
    The L2 regularization as a float.
    None if theta in an empty numpy.ndarray.
    
    Raises:
    This function should not raise any Exception.
    """

    l2_reg = 0.0
    for i in range(1, theta.shape[0]):
        l2_reg += theta[i, 0] ** 2
    return l2_reg

def l2(theta):
    """
    Computes the L2 regularization of a non-empty numpy.ndarray, without any for-loop.
    
    Args:
    theta: has to be a numpy.ndarray, a vector of shape n * 1.
    
    Returns:
    The L2 regularization as a float.
    None if theta in an empty numpy.ndarray.
    
    Raises:
    This function should not raise any Exception.
    """

    return np.sum(theta[1:] * theta[1:])

In [ ]:
x = np.array([2, 14, -13, 5, 12, 4, -19]).reshape((-1, 1))

iterative_l2(x) 
# Output: 911.0


911.0

In [ ]:
l2(x)

911

In [ ]:
y = np.array([3,0.5,-6]).reshape((-1, 1))
iterative_l2(y)
# Output: 36.25

36.25

In [ ]:
l2(y)
# Output: 36.25

36.25

# Exercise 02

In [ ]:
def reg_loss_(y, y_hat, theta, lambda_):
    """Computes the regularized loss of a linear regression model from two non-empty numpy.array, without any for loop.Args:
    y: has to be an numpy.ndarray, a vector of shape m * 1.
    y_hat: has to be an numpy.ndarray, a vector of shape m * 1.
    theta: has to be a numpy.ndarray, a vector of shape n * 1.
    lambda_: has to be a float.
    Returns:
    The regularized loss as a float.
    None if y, y_hat, or theta are empty numpy.ndarray.
    None if y and y_hat do not share the same shapes.
    Raises:
    This function should not raise any Exception.
    """
    m = len(y_hat)
    loss = 1/(2*m) * ( ((y_hat - y)**2).mean() + lambda_*l2(theta))
    return loss


In [ ]:
y = np.array([2, 14, -13, 5, 12, 4, -19]).reshape((-1, 1))
y_hat = np.array([3, 13, -11.5, 5, 11, 5, -20]).reshape((-1, 1))
theta = np.array([1, 2.5, 1.5, -0.9]).reshape((-1, 1))

reg_loss_(y, y_hat, theta, 0.5)
# Output: 0.8503571428571429

0.40647959183673465

In [ ]:
reg_loss_(y, y_hat, theta, 0.05)
# Output: 0.5511071428571429

0.1072295918367347

In [ ]:
reg_loss_(y, y_hat, theta, 0.9)
# Output: 1.116357142857143

0.6724795918367348

# Exercise 03

In [ ]:
def reg_log_loss_(y, y_hat, theta, lambda_):
    """
    Computes the regularized loss of a logistic regression model from two non-empty numpy.ndarray, without any for loops
    
    Args:
    y: has to be an numpy.ndarray, a vector of shape m * 1.
    y_hat: has to be an numpy.ndarray, a vector of shape m * 1.
    theta: has to be a numpy.ndarray, a vector of shape n * 1.
    lambda_: has to be a float.
    
    Returns:
    The regularized loss as a float.
    None if y, y_hat, or theta is empty numpy.ndarray.
    None if y and y_hat do not share the same shapes.
    
    Raises:
    This function should not raise any Exception.
    """

    m = y.shape[0]
    loss =  -1/m * np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat)) 
    l2_reg = 1/(2*m) * lambda_*l2(theta) 
    return  loss + l2_reg

In [ ]:
y = np.array([1, 1, 0, 0, 1, 1, 0]).reshape((-1, 1))
y_hat = np.array([.9, .79, .12, .04, .89, .93, .01]).reshape((-1, 1))
theta = np.array([1, 2.5, 1.5, -0.9]).reshape((-1, 1))
reg_log_loss_(y, y_hat, theta, .5)
# Output: 0.43377043716475955

0.43377043716476066

In [ ]:
# Example :
reg_log_loss_(y, y_hat, theta, .05)
# Output: 0.13452043716475953

0.13452043716476064

In [ ]:
# Example :
reg_log_loss_(y, y_hat, theta, .9)
# Output: 0.6997704371647596

0.6997704371647606

# Exercise 04

In [ ]:
def reg_linear_grad(y, x, theta, lambda_):
    """
    Computes the regularized linear gradient of three non-empty numpy.ndarray,
    with two for-loop. The three arrays must have compatible shapes.
    
    Args:
    y: has to be a numpy.ndarray, a vector of shape m * 1.
    x: has to be a numpy.ndarray, a matrix of dimesion m * n.
    theta: has to be a numpy.ndarray, a vector of shape (n + 1) * 1.
    lambda_: has to be a float.
    
    Return:
    A numpy.ndarray, a vector of shape (n + 1) * 1, containing the results of the formula for all j.
    None if y, x, or theta are empty numpy.ndarray.
    None if y, x or theta does not share compatibles shapes.
    None if y, x or theta or lambda_ is not of the expected type.
    
    Raises:
    This function should not raise any Exception.
    """
    
    m, n = x.shape
    X = np.c_[np.ones((m, 1)), x]
    theta_t = np.copy(theta)
    theta_t[0] = 0
    grad = np.zeros((n + 1, 1))
    
    for j in range(n + 1):
        for i in range(m):
            grad[j] += (X[i, :].dot(theta) - y[i]) * X[i, j]
        if j != 0:  # Skip regularization for j = 0
            grad[j] += lambda_ * theta_t[j]
        grad[j] /= m
        
    return grad

def vec_reg_linear_grad(y, x, theta, lambda_):
    """
    Computes the regularized linear gradient of three non-empty numpy.ndarray,
    without any for-loop. The three arrays must have compatible shapes.
    
    Args:
    y: has to be a numpy.ndarray, a vector of shape m * 1.
    x: has to be a numpy.ndarray, a matrix of dimesion m * n.
    theta: has to be a numpy.ndarray, a vector of shape (n + 1) * 1.
    lambda_: has to be a float.
    
    Return:
    A numpy.ndarray, a vector of shape (n + 1) * 1, containing the results of the formula for all j.
    None if y, x, or theta are empty numpy.ndarray.
    None if y, x or theta does not share compatibles shapes.
    None if y, x or theta or lambda_ is not of the expected type.
    
    Raises:
    This function should not raise any Exception.
    """

    m, n = x.shape
    X = np.c_[np.ones((m, 1)), x]
    theta_t = np.copy( theta)
    theta_t[0] = 0
    return 1/m * (X.T@(X@theta - y) + (lambda_ * theta_t))

In [ ]:
x = np.array([
    [ -6, -7, -9],
    [ 13, -2, 14],
    [ -7, 14, -1],
    [ -8, -4, 6],
    [ -5, -9, 6],
    [ 1, -5, 11],
    [ 9, -11, 8]])
y = np.array([[2], [14], [-13], [5], [12], [4], [-19]])
theta = np.array([[7.01], [3], [10.5], [-6]])
reg_linear_grad(y, x, theta, 1)
# Output: array([[ -60.99 ],[-195.64714286],[ 863.46571429], [-644.52142857]])

array([[ -60.99      ],
       [-195.64714286],
       [ 863.46571429],
       [-644.52142857]])

In [ ]:
vec_reg_linear_grad(y, x, theta, 1)
# Output: array([[ -60.99 ],[-195.64714286],[ 863.46571429],[-644.52142857]])

array([[ -60.99      ],
       [-195.64714286],
       [ 863.46571429],
       [-644.52142857]])

In [ ]:
reg_linear_grad(y, x, theta, 0.5)
# Output: array([[ -60.99 ], [-195.86142857], [ 862.71571429], [-644.09285714]])

array([[ -60.99      ],
       [-195.86142857],
       [ 862.71571429],
       [-644.09285714]])

In [ ]:
vec_reg_linear_grad(y, x, theta, 0.5)
# Output:array([[ -60.99 ],[-195.86142857],[ 862.71571429],[-644.09285714]])

array([[ -60.99      ],
       [-195.86142857],
       [ 862.71571429],
       [-644.09285714]])

In [ ]:
reg_linear_grad(y, x, theta, 0.0)
# Output:array([[ -60.99 ],[-196.07571429],[ 861.96571429],[-643.66428571]])

array([[ -60.99      ],
       [-196.07571429],
       [ 861.96571429],
       [-643.66428571]])

In [ ]:
vec_reg_linear_grad(y, x, theta, 0.0)
# Output:array([[ -60.99 ],[-196.07571429],[ 861.96571429],[-643.66428571]])

array([[ -60.99      ],
       [-196.07571429],
       [ 861.96571429],
       [-643.66428571]])

# Exercise 05 : 

In [ ]:
def sigmoid_(x): return 1 / (1 + np.exp(-x))

def logistic_predict_(x, theta):
    m,n = x.shape
    x_bias = np.c_[np.ones((m, 1)), x]
    return sigmoid_(np.dot(x_bias, theta))

def reg_logistic_grad(y, x, theta, lambda_):
    """
    Computes the regularized logistic gradient of three non-empty numpy.ndarray, with two for-loops. The three arrayArgs:
    y: has to be a numpy.ndarray, a vector of shape m * 1.
    x: has to be a numpy.ndarray, a matrix of dimesion m * n.
    theta: has to be a numpy.ndarray, a vector of shape n * 1.
    lambda_: has to be a float.
    
    Returns:
    A numpy.ndarray, a vector of shape n * 1, containing the results of the formula for all j.
    None if y, x, or theta are empty numpy.ndarray.
    None if y, x or theta does not share compatibles shapes.
    
    Raises:
    This function should not raise any Exception.
    """
    
    m, n = x.shape
    X = np.c_[np.ones((m, 1)), x]
    theta_t = np.copy(theta)
    theta_t[0] = 0
    grad = np.zeros((n + 1, 1))
    for j in range(n + 1):
        for i in range(m):
            grad[j] += (sigmoid_(X[i, :] @ theta) - y[i]) * X[i, j]
        if j != 0: grad[j] += lambda_ * theta_t[j]
    grad = grad / m
    return grad
        

def vec_reg_logistic_grad(y, x, theta, lambda_):
    """
    Computes the regularized logistic gradient of three non-empty numpy.ndarray, without any for-loop. The three arrArgs:
    y: has to be a numpy.ndarray, a vector of shape m * 1.
    x: has to be a numpy.ndarray, a matrix of shape m * n.
    theta: has to be a numpy.ndarray, a vector of shape n * 1.
    lambda_: has to be a float.
    
    Returns:
    A numpy.ndarray, a vector of shape n * 1, containing the results of the formula for all j.
    None if y, x, or theta are empty numpy.ndarray.
    None if y, x or theta does not share compatibles shapes.
    
    Raises:
    This function should not raise any Exception.
    """
    
    m, n = x.shape
    X = np.c_[np.ones((m, 1)), x]
    theta_t = np.copy( theta)
    theta_t[0] = 0
    return 1/m * (X.T@(logistic_predict_(x, theta) - y) + (lambda_ * theta_t))

In [ ]:
x = np.array([[0, 2, 3, 4],
              [2, 4, 5, 5],
              [1, 3, 2, 7]])
y = np.array([[0], [1], [1]])
theta = np.array([[-2.4], [-1.5], [0.3], [-1.4], [0.7]])

reg_logistic_grad(y, x, theta, 1)
# Output: array([[-0.55711039],[-1.40334809],[-1.91756886],[-2.56737958],[-3.03924017]])

array([[-0.55711039],
       [-1.40334809],
       [-1.91756886],
       [-2.56737958],
       [-3.03924017]])

In [ ]:
# Example 1.2:
vec_reg_logistic_grad(y, x, theta, 1)
# Output:array([[-0.55711039],[-1.40334809],[-1.91756886],[-2.56737958],[-3.03924017]])

array([[-0.55711039],
       [-1.40334809],
       [-1.91756886],
       [-2.56737958],
       [-3.03924017]])

In [ ]:
reg_logistic_grad(y, x, theta, 0.5)
# Output: array([[-0.55711039], [-1.15334809], [-1.96756886], [-2.33404624], [-3.15590684]])

array([[-0.55711039],
       [-1.15334809],
       [-1.96756886],
       [-2.33404624],
       [-3.15590684]])

In [ ]:
vec_reg_logistic_grad(y, x, theta, 0.5)
# Output: array([[-0.55711039], [-1.15334809],[-1.96756886], [-2.33404624], [-3.15590684]])

array([[-0.55711039],
       [-1.15334809],
       [-1.96756886],
       [-2.33404624],
       [-3.15590684]])

In [ ]:
reg_logistic_grad(y, x, theta, 0.0)
# Output: array([[-0.55711039], [-0.90334809],[-2.01756886], [-2.10071291], [-3.27257351]])

array([[-0.55711039],
       [-0.90334809],
       [-2.01756886],
       [-2.10071291],
       [-3.27257351]])

In [ ]:
vec_reg_logistic_grad(y, x, theta, 0.0)
# Output: array([[-0.55711039], [-0.90334809], [-2.01756886], [-2.10071291], [-3.27257351]])

array([[-0.55711039],
       [-0.90334809],
       [-2.01756886],
       [-2.10071291],
       [-3.27257351]])

# Exercise 06 : 

In [ ]:
class MyLinearRegression():
    """
    Description:
    My personnal linear regression class to fit like a boss.
    """
    def __init__(self, thetas, alpha=0.001, max_iter=1000):
        self.alpha = alpha
        self.max_iter = max_iter
        self.thetas = thetas

    def fit_(self, x, y):
        self.thetas = theta.astype(np.float64)
        for i in range(self.max_iter):
            grad = simple_gradient(x, y, self.thetas)
            self.thetas-= grad.astype(np.float64) * self.alpha
        return self.thetas

    def add_intercept(self, x):
        """
        Adds a column of 1’s to the non-empty numpy.array x.
        
        Args:
        x: has to be a numpy.array of dimension m * n.
        
        Returns:
        X, a numpy.array of dimension m * (n + 1).
        None if x is not a numpy.array.
        None if x is an empty numpy.array.
        
        Raises:
        This function should not raise any Exception.
        """
    
        if not isinstance(x, np.ndarray) or x.size == 0:
            return None
    
        if len(x.shape) == 1: x = x.reshape(x.shape[0], 1)
        
        ones = np.ones((x.shape[0], 1))
        X = np.hstack((ones, x))
        return X
    
    def predict_(self, x):
        """
        Computes the vector of prediction y_hat from two non-empty numpy.array.
        
        Args:
        x: has to be an numpy.array, a vector of dimension m * 1.
        theta: has to be an numpy.array, a vector of dimension 2 * 1.
        
        Returns:
        y_hat as a numpy.array, a vector of dimension m * 1.
        None if x and/or theta are not numpy.array.
        None if x or theta are empty numpy.array.
        None if x or theta dimensions are not appropriate.
        
        Raises:
        This function should not raise any Exceptions.
        """
    
        if not (isinstance(x, np.ndarray) and isinstance(self.thetas, np.ndarray)):
            return None
    
        if x.size == 0 or self.thetas.size == 0:
            return None
    
        if self.thetas.shape != (2,1):
             return None

        return self.add_intercept(x) @ self.thetas

    
    def loss_elem_(self, y, y_hat):
        if not (isinstance(y, np.ndarray) and isinstance(y_hat, np.ndarray)):
            return None
        
        if y.shape != y_hat.shape:
            return None
    
        J_elem = np.zeros(y.shape)
        for i in range(len(y)):
            J_elem[i] = (y[i] - y_hat[i]) ** 2

        return J_elem
        
    def loss_(self, y, y_hat):
        
        J_elem = self.loss_elem_(y, y_hat)
        if J_elem is None:
            return None
    
        J_value = 0.0
        for elem in J_elem:
            J_value += elem
        J_value /= (2 * len(J_elem))
    
        return float(J_value)

    @staticmethod
    def mse_(y, y_hat):
        """
        Description:
        Calculate the MSE between the predicted output and the real output.
        
        Args:
        y: has to be a numpy.array, a vector of dimension m * 1.
        y_hat: has to be a numpy.array, a vector of dimension m * 1.
        
        Returns:
        mse: has to be a float.
        None if there is a matching dimension problem.
        
        Raises:
        This function should not raise any Exceptions.
        """
        return ((y - y_hat) ** 2).mean()

    @classmethod
    def rmse_(y, y_hat):
        """
        Description:
        Calculate the RMSE between the predicted output and the real output.
        Args:
        y: has to be a numpy.array, a vector of dimension m * 1.
        y_hat: has to be a numpy.array, a vector of dimension m * 1.
        Returns:
        rmse: has to be a float.
        None if there is a matching dimension problem.
        Raises:
        This function should not raise any Exceptions.
        """
        return sqrt(mse_(y, y_hat))
    
    @classmethod
    def mae_(y, y_hat):
        """
        Description:
        Calculate the MAE between the predicted output and the real output.
        Args:
        y: has to be a numpy.array, a vector of dimension m * 1.
        y_hat: has to be a numpy.array, a vector of dimension m * 1.
        Returns:
        mae: has to be a float.
        None if there is a matching dimension problem.
        Raises:
        This function should not raise any Exceptions.
        """
        return np.abs(y - y_hat).mean()

    @classmethod
    def r2score_(y, y_hat):
        """
        Description:
        Calculate the R2score between the predicted output and the output.
        Args:
        y: has to be a numpy.array, a vector of dimension m * 1.
        y_hat: has to be a numpy.array, a vector of dimension m * 1.
        Returns:
        r2score: has to be a float.
        None if there is a matching dimension problem.
        Raises:
        This function should not raise any Exceptions.
        """
        return 1 - (((y - y_hat) ** 2).sum() / ((y - y.mean()) ** 2).sum())

In [ ]:
class MyRidge(MyLinearRegression):
    """
    Description:
    My personal ridge regression class to fit like a boss.
    """

    def __init__(self, thetas, alpha=0.001, max_iter=1000, lambda_=0.5):
        """
        Initialize the MyRidge object.

        Parameters:
        - thetas: numpy array of shape (n_features,) representing the initial model coefficients
        - alpha: learning rate for gradient descent (default: 0.001)
        - max_iter: maximum number of iterations for gradient descent (default: 1000)
        - lambda_: regularization parameter (default: 0.5)
        """

        self.alpha = alpha
        self.max_iter = max_iter
        self.thetas = thetas
        self.lambda_ = lambda_

    def get_params_(self):
        """
        Get the parameters of the estimator.

        Returns:
        - params: dictionary containing the parameters of the estimator
        """

        return self.thetas

    def set_params_(self, **params):
        """
        Set the parameters of the estimator.

        Parameters:
        - params: dictionary containing the new parameter values
        """
        # self.thetas = 

    def loss_(self, y_true, y_pred):
        """
        Calculate the loss between two vectors.

        Parameters:
        - y_true: numpy array of shape (n_samples,) representing the true values
        - y_pred: numpy array of shape (n_samples,) representing the predicted values

        Returns:
        - loss: float value representing the loss
        """

        return reg_loss_(y_true, y_pred , self.thetas, self.lambda_)

    def loss_elem_(self, y_true, y_pred):
        """
        Calculate a vector corresponding to the squared difference between two vectors.

        Parameters:
        - y_true: numpy array of shape (n_samples,) representing the true values
        - y_pred: numpy array of shape (n_samples,) representing the predicted values

        Returns:
        - loss_elem: numpy array of shape (n_samples,) representing the element-wise squared difference
        """

        return ((y_pred - y_true) ** 2).mean()

    def gradient_(self, X, y):
        """
        Calculate the vectorized regularized gradient.

        Parameters:
        - X: numpy array of shape (n_samples, n_features) representing the input features
        - y: numpy array of shape (n_samples,) representing the true values

        Returns:
        - gradient: numpy array of shape (n_features,) representing the gradient
        """

        return vec_reg_linear_grad(y, X, self.thetas, self.lambda_)

    def fit_(self, X, y):
        """
        Fit the Ridge regression model to a training dataset.

        Parameters:
        - X: numpy array of shape (n_samples, n_features) representing the input features
        - y: numpy array of shape (n_samples,) representing the true values
        """

        for i in range(self.max_iter):
            grad = self.gradient_(X, y)
            self.thetas-= grad * self.alpha
        return self.thetas


# Exercise 07 : 

# Exercise 08 : 

In [ ]:
from sklearn.metrics import *

In [ ]:
class MyLogisticRegression():
    """
    Description:
    My personnal logistic regression to classify things.
    """
    supported_penalities = ['l2'] # We consider l2 penality only. One may wants to implement other penalities
    def __init__(self, theta, alpha=0.001, max_iter=1000, penality='l2', lambda_=1.0):
        self.alpha = alpha
        self.max_iter = max_iter
        self.theta = theta
        self.penality = penality
        self.lambda_ = lambda_ if penality in self.supported_penalities else 0

    def predict_(self, x):
        
        def sigmoid_(x): return 1 / (1 + np.exp(-x))
        
        m,n = x.shape
        x_bias = np.c_[np.ones((m, 1)), x]
        return sigmoid_(np.dot(x_bias, self.theta))
        
    def loss_elem_(self, y, yhat):
        return reg_log_loss_(y, y_hat, self.thetas, self.lambda_)


    def loss_(self, X, y):
        y_hat = self.predict_(X)
        eps = 1e-15
        m = y.shape[0]
        y_hat = np.clip(y_hat, eps, 1 - eps)

        return reg_log_loss_(y, y_hat, self.thetas, self.lambda_)
    
    
    def fit_(self, x, y):
        
        def vec_log_gradient(x, y, theta):
            m, n = x.shape
            X = np.c_[np.ones((m, 1)), x]
            return 1/m * X.T@(self.predict_(x) - y)
        
        for i in range(self.max_iter):
            grad = vec_reg_linear_grad(y, x, self.thetas, self.lambda_)
            self.theta -= grad * self.alpha
        return self.theta

In [ ]:
theta = np.array([[-2.4], [-1.5], [0.3], [-1.4], [0.7]])
model1 = MyLogisticRegression(theta, lambda_=5.0)
print(model1.penality) # Output ’l2’
print(model1.lambda_) # Output 5.0

l2
5.0


In [ ]:
model2 = MyLogisticRegression(theta, penality=None)
print(model2.penality) # Output None
print(model2.lambda_) # Output 0.0

None
0


In [ ]:
model3 = mylogr(theta, penality=None, lambda_=2.0)
model3.penality # Output None
model3.lambda_ # Output 0.0