In [ ]:
import numpy as np

# Exercise 00

In [ ]:
def simple_predict(x, theta):
    """
    Computes the prediction vector y_hat from two non-empty numpy.array.
    
    Args:
    x: has to be an numpy.array, a matrix of dimension m * n.
    theta: has to be an numpy.array, a vector of dimension (n + 1) * 1.
    
    Return:
    y_hat as a numpy.array, a vector of dimension m * 1.
    None if x or theta are empty numpy.array.
    None if x or theta dimensions are not matching.
    None if x or theta is not of expected type.
    
    Raises:
    This function should not raise any Exception.
    """
    if type(x) != np.ndarray or type(theta) != np.ndarray or x.size == 0 or theta.size == 0:
        return None
    if x.shape[1] + 1 != theta.shape[0] or len(theta.shape) != 2 or theta.shape[1] != 1:
        return None
    m = x.shape[0]
    y_hat = np.zeros((m, 1))
    for i in range(m):
        y_hat[i] = theta[0]  # bias term
        for j in range(1, theta.shape[0]):
            y_hat[i] += x[i, j-1] * theta[j]
    return y_hat

In [ ]:
x = np.arange(1,13).reshape((4,-1))
theta1 = np.array([5, 0, 0, 0]).reshape((-1, 1))

simple_predict(x, theta1)
# Ouput: array([[5.], [5.], [5.], [5.]])
# Do you understand why y_hat contains only 5’s here?

array([[5.],
       [5.],
       [5.],
       [5.]])

In [ ]:
# Example 2:
theta2 = np.array([0, 1, 0, 0]).reshape((-1, 1))
simple_predict(x, theta2)
# Output: array([[ 1.], [ 4.], [ 7.], [10.]])
# Do you understand why y_hat == x[:,0] here?

array([[ 1.],
       [ 4.],
       [ 7.],
       [10.]])

# Exercise 01

In [ ]:
def predict_(x, theta):
    """Computes the prediction vector y_hat from two non-empty numpy.array.
    Args:
    x: has to be an numpy.array, a vector of dimensions m * n.
    theta: has to be an numpy.array, a vector of dimensions (n + 1) * 1.
    Return:
    y_hat as a numpy.array, a vector of dimensions m * 1.
    None if x or theta are empty numpy.array.
    None if x or theta dimensions are not appropriate.
    None if x or theta is not of expected type.
    Raises:
    This function should not raise any Exception.
    """

    if type(x) != np.ndarray or type(theta) != np.ndarray or x.size == 0 or theta.size == 0:
        return None
    if x.shape[1] + 1 != theta.shape[0] or len(theta.shape) != 2 or theta.shape[1] != 1:
        return None

    ones = np.ones((x.shape[0], 1))
    X = np.hstack((ones, x))
    return X @ theta

In [ ]:
import numpy as np
x = np.arange(1,13).reshape((4,-1))
theta1 = np.array([5, 0, 0, 0]).reshape((-1, 1))
predict_(x, theta1)
# Ouput: array([[5.], [5.], [5.], [5.]])
# Do you understand why y_hat contains only 5’s here?

array([[5.],
       [5.],
       [5.],
       [5.]])

In [ ]:
theta2 = np.array([0, 1, 0, 0]).reshape((-1, 1))
predict_(x, theta2)
# Output: array([[ 1.], [ 4.], [ 7.], [10.]])
# Do you understand why y_hat == x[:,0] here?

array([[ 1.],
       [ 4.],
       [ 7.],
       [10.]])

In [ ]:
theta3 = np.array([-1.5, 0.6, 2.3, 1.98]).reshape((-1, 1))
predict_(x, theta3)
# Output: array([[ 9.64], [24.28], [38.92], [53.56]])

array([[ 9.64],
       [24.28],
       [38.92],
       [53.56]])

In [ ]:
theta4 = np.array([-3, 1, 2, 3.5]).reshape((-1, 1))
predict_(x, theta4)
# Output: array([[12.5], [32. ], [51.5], [71. ]])

array([[12.5],
       [32. ],
       [51.5],
       [71. ]])

# Exercise 02

In [ ]:
def loss_(y, y_hat):
    """Computes the mean squared error of two non-empty numpy.array, without any for loop.
    The two arrays must have the same dimensions.
    Args:
    y: has to be an numpy.array, a vector.
    y_hat: has to be an numpy.array, a vector.
    Return:
    The mean squared error of the two vectors as a float.
    None if y or y_hat are empty numpy.array.
    None if y and y_hat does not share the same dimensions.
    None if y or y_hat is not of expected type.
    Raises:
    This function should not raise any Exception.
    """
    return ((y_hat - y) ** 2).mean() * .5

In [ ]:
import numpy as np
X = np.array([0, 15, -9, 7, 12, 3, -21]).reshape((-1, 1))
Y = np.array([2, 14, -13, 5, 12, 4, -19]).reshape((-1, 1))
# Example 1:
loss_(X, Y)
# Output: 2.142857142857143

2.142857142857143

In [ ]:
# Example 2:
loss_(X, X)
# Output: 0.0

0.0

# Exercise 03

In [ ]:

import numpy as np

def add_intercept(x):
    """Append a column of ones to numpy array x."""
    return np.concatenate((np.ones((x.shape[0], 1)), x), axis=1)

def predict_(x, theta):
    """Compute linear regression prediction."""
    return add_intercept(x) @ theta

def gradient(x, y, theta):
    """Computes a gradient vector from three non-empty numpy.array, without any for-loop.
    The three arrays must have the compatible dimensions.
    Args:
    x: has to be an numpy.array, a matrix of dimension m * n.
    y: has to be an numpy.array, a vector of dimension m * 1.
    theta: has to be an numpy.array, a vector (n +1) * 1.
    Return:
    The gradient as a numpy.array, a vector of dimensions n * 1,
    containg the result of the formula for all j.
    None if x, y, or theta are empty numpy.array.
    None if x, y and theta do not have compatible dimensions.
    None if x, y or theta is not of expected type.
    Raises:
    This function should not raise any Exception.
    """
    # if type(x) != np.ndarray or type(theta) != np.ndarray or x.size == 0 or theta.size == 0:
    #     return None
    # if x.shape[1] + 1 != theta.shape[0] or len(theta.shape) != 2 or theta.shape[1] != 1:
    #     return None
    
    m, n = x.shape
    # if y.shape != (m, 1) or theta.shape != (n + 1, 1):
    #     return None

    # Add a bias term to x
    x_bias = np.c_[np.ones((m, 1)), x]

    # Calculate the gradient
    gradients = 1.0/m * x_bias.T.dot(x_bias.dot(theta) - y)

    return gradients

In [ ]:
import numpy as np
x = np.array([
[ -6, -7, -9],
[ 13, -2, 14],
[ -7, 14, -1],
[ -8, -4, 6],
[ -5, -9, 6],
[ 1, -5, 11],
[ 9, -11, 8]])
y = np.array([2, 14, -13, 5, 12, 4, -19]).reshape((-1, 1))
theta1 = np.array([1, 3, 0.5,-6]).reshape((-1, 1))
# Example :
# gradient(x, y, theta1)
# Output: array([[ -33.71428571], [ -37.35714286], [183.14285714], [-393.]])

In [ ]:
m, n = x.shape
# if y.shape != (m, 1) or theta.shape != (n + 1, 1):
#     return None

# Add a bias term to x
x_bias = np.c_[np.ones((m, 1)), x]
x_bias

array([[  1.,  -6.,  -7.,  -9.],
       [  1.,  13.,  -2.,  14.],
       [  1.,  -7.,  14.,  -1.],
       [  1.,  -8.,  -4.,   6.],
       [  1.,  -5.,  -9.,   6.],
       [  1.,   1.,  -5.,  11.],
       [  1.,   9., -11.,   8.]])

In [ ]:
theta1

array([[ 1. ],
       [ 3. ],
       [ 0.5],
       [-6. ]])

In [ ]:
(x_bias.dot(theta1) - y)

array([[ 31.5],
       [-59. ],
       [  6. ],
       [-66. ],
       [-66.5],
       [-68.5],
       [ -6.5]])

In [ ]:
1.0/m * x_bias.T.dot((x_bias.dot(theta1) - y))

array([[ -32.71428571],
       [ -37.78571429],
       [ 179.71428571],
       [-388.        ]])

In [ ]:
t

array([[ 1. ,  1. ],
       [ 1. ,  3. ],
       [ 1. ,  0.5],
       [ 1. , -6. ]])

In [ ]:
# Example :
theta2 = np.array([0,0,0]).reshape((-1, 1))
gradient(x, y, theta2)
# Output:
array([[ -0.71428571], [ 0.85714286], [23.28571429], [-26.42857143]])

ValueError: shapes (7,4) and (3,1) not aligned: 4 (dim 1) != 3 (dim 0)

# Exercise 04

In [ ]:
def fit_(x, y, theta, alpha, max_iter):
    """
    Description:
    Fits the model to the training dataset contained in x and y.
    Args:
    x: has to be a numpy.array, a matrix of dimension m * n:
    (number of training examples, number of features).
    y: has to be a numpy.array, a vector of dimension m * 1:
    (number of training examples, 1).
    theta: has to be a numpy.array, a vector of dimension (n + 1) * 1:
    (number of features + 1, 1).
    alpha: has to be a float, the learning rate
    max_iter: has to be an int, the number of iterations done during the gradient descent
    Return:
    new_theta: numpy.array, a vector of dimension (number of features + 1, 1).
    None if there is a matching dimension problem.
    None if x, y, theta, alpha or max_iter is not of expected type.
    Raises:
    This function should not raise any Exception.
    """

    theta = theta.astype(np.float64)
    for i in range(max_iter):
        grad = simple_gradient(x, y, theta)
        theta -= grad.astype(np.float64) * alpha
    return theta

In [ ]:
import numpy as np
x = np.array([[0.2, 2., 20.], [0.4, 4., 40.], [0.6, 6., 60.], [0.8, 8., 80.]])
y = np.array([[19.6], [-2.8], [-25.2], [-47.6]])
theta = np.array([[42.], [1.], [1.], [1.]])
# Example 0:
theta2 = fit_(x, y, theta, alpha = 0.0005, max_iter=42000)
theta2
# Output:
array([[41.99..],[0.97..], [0.77..], [-1.20..]])
# Example 1:
predict_(x, theta2)
# Output:
array([[19.5992..], [-2.8003..], [-25.1999..], [-47.5996..]])

# Exercise 05

In [ ]:
import numpy as np
from mylinearregression import MyLinearRegression as MyLR
X = np.array([[1., 1., 2., 3.], [5., 8., 13., 21.], [34., 55., 89., 144.]])
Y = np.array([[23.], [48.], [218.]])
mylr = MyLR([[1.], [1.], [1.], [1.], [1]])
# Example 0:
y_hat = mylr.predict_(X)
# Output:
array([[8.], [48.], [323.]])
# Example 1:
mylr.loss_elem_(Y, y_hat)
# Output:
array([[225.], [0.], [11025.]])
# Example 2:
mylr.loss_(Y, y_hat)
# Output:
1875.0
# Example 3:
mylr.alpha = 1.6e-4
mylr.max_iter = 200000
mylr.fit_(X, Y)
mylr.theta
# Output:
array([[18.188..], [2.767..], [-0.374..], [1.392..], [0.017..]])
# Example 4:
y_hat = mylr.predict_(X)
# Output:
array([[23.417..], [47.489..], [218.065...]])
# Example 5:
mylr.loss_elem_(Y, y_hat)
# Output:
array([[0.174..], [0.260..], [0.004..]])
# Example 6:
mylr.loss_(Y, y_hat)
# Output:
0.0732..

# Exercise 06

In [ ]:
import pandas as pd
import numpy as np
from mylinearregression import MyLinearRegression as MyLR
data = pd.read_csv("spacecraft_data.csv")
X = np.array(data[[’Age’]])
Y = np.array(data[[’Sell_price’]])
myLR_age = MyLR(theta = [[1000.0], [-1.0]], alpha = 2.5e-5, max_iter = 100000)
myLR_age.fit_(X[:,0].reshape(-1,1), Y)
y_pred = myLR_age.predict_(X[:,0].reshape(-1,1))
myLR_age.mse_(y_pred,Y)
#Output
55736.86719...

In [ ]:
import pandas as pd
import numpy as np
from mylinearregression import MyLinearRegression as MyLR
data = pd.read_csv("spacecraft_data.csv")
X = np.array(data[[’Age’,’Thrust_power’,’Terameters’]])
Y = np.array(data[[’Sell_price’]])
my_lreg = MyLR(theta = [1.0, 1.0, 1.0, 1.0], , alpha = 1e-4, max_iter = 600000)
# Example 0:
my_lreg.mse_(X,Y)
# Output:
144044.877...
# Example 1:
my_lreg.fit_(X,Y)
my_lreg.theta
# Output:
array([[334.994...],[-22.535...],[5.857...],[-2.586...]])
# Example 2:
my_lreg.mse_(X,Y)
# Output:
586.896999...

In [ ]:
# Example 1:
X = np.array([0, 15, -9, 7, 12, 3, -21]).reshape((-1, 1))
minmax(X)
# Output:
array([0.58333333, 1. , 0.33333333, 0.77777778, 0.91666667,
0.66666667, 0. ])
# Example 2:
Y = np.array([2, 14, -13, 5, 12, 4, -19]).reshape((-1, 1))
minmax(Y)
# Output:
array([0.63636364, 1. , 0.18181818, 0.72727273, 0.93939394,
0.6969697 , 0. ])

# Exercise 07

In [ ]:
def add_polynomial_features(x, power):
    """Add polynomial features to vector x by raising its values up to the power given in argument.
    Args:
    x: has to be an numpy.array, a vector of dimension m * 1.
    power: has to be an int, the power up to which the components of vector x are going to be raised.
    Return:
    The matrix of polynomial features as a numpy.array, of dimension m * n,
    containing the polynomial feature values for all training examples.
    None if x is an empty numpy.array.
    None if x or power is not of expected type.
    Raises:
    This function should not raise any Exception.
    """
    pass

In [ ]:
import numpy as np
x = np.arange(1,6).reshape(-1, 1)
# Example 0:
add_polynomial_features(x, 3)
# Output:
array([[ 1, 1, 1],
[ 2, 4, 8],
[ 3, 9, 27],
[ 4, 16, 64],
[ 5, 25, 125]])
# Example 1:
add_polynomial_features(x, 6)
# Output:
array([[ 1, 1, 1, 1, 1, 1],
[ 2, 4, 8, 16, 32, 64],
[ 3, 9, 27, 81, 243, 729],
[ 4, 16, 64, 256, 1024, 4096],
[ 5, 25, 125, 625, 3125, 15625]])

# Exercise 08

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
x = np.arange(1,11).reshape(-1,1)
y = np.array([[ 1.39270298],
[ 3.88237651],
[ 4.37726357],
[ 4.63389049],
[ 7.79814439],
[ 6.41717461],
[ 8.63429886],
[ 8.19939795],
[10.37567392],
[10.68238222]])
plt.scatter(x,y)
plt.show()

In [ ]:
from polynomial_model import add_polynomial_features
from mylinearregression import MyLinearRegression as MyLR
# Build the model:
x_ = add_polynomial_features(x, 3)
my_lr = MyLR(np.ones(4).reshape(-1,1)).fit_(x_, y)
# Plot:
## To get a smooth curve, we need a lot of data points
continuous_x = np.arange(1,10.01, 0.01).reshape(-1,1)
x_ = add_polynomial_features(continuous_x, 3)
y_hat = my_lr.predict_(continuous_x)
plt.scatter(x,y)
plt.plot(continuous_x, y_hat, color=’orange’)
plt.show()

# Exercise 09