In [ ]:
import numpy as np

# Exercise 00

In [ ]:
def add_intercept(x):
    """
    Adds a column of 1’s to the non-empty numpy.array x.
    
    Args:
    x: has to be a numpy.array of dimension m * n.
    
    Returns:
    X, a numpy.array of dimension m * (n + 1).
    None if x is not a numpy.array.
    None if x is an empty numpy.array.
    
    Raises:
    This function should not raise any Exception.
    """

    if not isinstance(x, np.ndarray) or x.size == 0:
        return None

    if len(x.shape) == 1: x = x.reshape(x.shape[0], 1)
    
    ones = np.ones((x.shape[0], 1))
    X = np.hstack((ones, x))
    return X
    
def predict_(x, theta):
    """
    Computes the vector of prediction y_hat from two non-empty numpy.array.
    
    Args:
    x: has to be an numpy.array, a vector of dimension m * 1.
    theta: has to be an numpy.array, a vector of dimension 2 * 1.
    
    Returns:
    y_hat as a numpy.array, a vector of dimension m * 1.
    None if x and/or theta are not numpy.array.
    None if x or theta are empty numpy.array.
    None if x or theta dimensions are not appropriate.
    
    Raises:
    This function should not raise any Exceptions.
    """

    if not (isinstance(x, np.ndarray) and isinstance(theta, np.ndarray)):
        return None

    if x.size == 0 or theta.size == 0:
        return None

    if theta.shape != (2,1):
         return None

    return add_intercept(x) @ theta

def simple_gradient(x, y, theta):
    """
    Computes a gradient vector from three non-empty numpy.array, with a for-loop.
    The three arrays must have compatible shapes.
    
    Args:
    x: has to be an numpy.array, a vector of shape m * 1.
    y: has to be an numpy.array, a vector of shape m * 1.
    theta: has to be an numpy.array, a 2 * 1 vector.
    
    Return:
    The gradient as a numpy.array, a vector of shape 2 * 1.
    None if x, y, or theta are empty numpy.array.
    None if x, y and theta do not have compatible shapes.
    None if x, y or theta is not of the expected type.
    
    Raises:
    This function should not raise any Exception.
    """
    nabla_w = 0.0
    nabla_b = 0.0
    y_hat = predict_(x, theta)

    for i in range(x.shape[0]):
        nabla_w += (y_hat[i] - y[i]) * x[i]
        nabla_b += y_hat[i] - y[i]
    nabla_w = nabla_w * (1 / x.shape[0])
    nabla_b = nabla_b * (1 / x.shape[0])
    return np.array([nabla_b, nabla_w])

In [ ]:
x = np.array([12.4956442, 21.5007972, 31.5527382, 48.9145838, 57.5088733]).reshape((-1, 1))
y = np.array([37.4013816, 36.1473236, 45.7655287, 46.6793434, 59.5585554]).reshape((-1, 1))
# Example 0:
theta1 = np.array([2, 0.7]).reshape((-1, 1))
simple_gradient(x, y, theta1)
# Output: array([[-19.0342574], [-586.66875564]])

array([[ -19.0342574 ],
       [-586.66875564]])

In [ ]:
# Example 1:
theta2 = np.array([1, -0.4]).reshape((-1, 1))
simple_gradient(x, y, theta2)
# Output: array([[-57.86823748], [-2230.12297889]])

array([[  -57.86823748],
       [-2230.12297889]])

# Exercise 01

In [ ]:
def simple_gradient(x, y, theta):
    """Computes a gradient vector from three non-empty numpy.array, without any for loop.
    The three arrays must have compatible shapes.
    Args:
    x: has to be a numpy.array, a matrix of shape m * 1.
    y: has to be a numpy.array, a vector of shape m * 1.
    theta: has to be a numpy.array, a 2 * 1 vector.
    Return:
    The gradient as a numpy.ndarray, a vector of dimension 2 * 1.
    None if x, y, or theta is an empty numpy.ndarray.
    None if x, y and theta do not have compatible dimensions.
    Raises:
    This function should not raise any Exception.
    """
    y_hat = predict_(x, theta)
    m = x.shape[0]
    
    return (1/m) * add_intercept(x).T @ (y_hat - y)

In [ ]:
import numpy as np
x = np.array([12.4956442, 21.5007972, 31.5527382, 48.9145838, 57.5088733]).reshape((-1, 1))
y = np.array([37.4013816, 36.1473236, 45.7655287, 46.6793434, 59.5585554]).reshape((-1, 1))
# Example 0:
theta1 = np.array([2, 0.7]).reshape((-1, 1))
simple_gradient(x, y, theta1)
# Output: array([[-19.0342...], [-586.6687...]])

array([[ -19.0342574 ],
       [-586.66875564]])

In [ ]:
# Example 1:
theta2 = np.array([1, -0.4]).reshape((-1, 1))
simple_gradient(x, y, theta2)
# Output: array([[-57.8682...], [-2230.1229...]])

array([[  -57.86823748],
       [-2230.12297889]])

In [ ]:
y_hat = predict_(x, theta1)
m = x.shape[0]
y_hat, m

(array([[10.74695094],
        [17.05055804],
        [24.08691674],
        [36.24020866],
        [42.25621131]]),
 5)

In [ ]:
diff =  (y_hat - y)
diff

array([[-26.65443066],
       [-19.09676556],
       [-21.67861196],
       [-10.43913474],
       [-17.30234409]])

In [ ]:
x_T = add_intercept(x).T 
x_T

array([[ 1.       ,  1.       ,  1.       ,  1.       ,  1.       ],
       [12.4956442, 21.5007972, 31.5527382, 48.9145838, 57.5088733]])

In [ ]:
out = x_T @ diff
out

array([[  -95.17128701],
       [-2933.34377818]])

In [ ]:
(1/m) * out

array([[ -19.0342574 ],
       [-586.66875564]])

# Exercise 02

In [ ]:
def fit_(x, y, theta, alpha, max_iter):
    """
    Description:
    Fits the model to the training dataset contained in x and y.
    Args:
    x: has to be a numpy.ndarray, a vector of dimension m * 1: (number of training examples, 1).
    y: has to be a numpy.ndarray, a vector of dimension m * 1: (number of training examples, 1).
    theta: has to be a numpy.ndarray, a vector of dimension 2 * 1.
    alpha: has to be a float, the learning rate
    max_iter: has to be an int, the number of iterations done during the gradient descent
    Returns:
    new_theta: numpy.ndarray, a vector of dimension 2 * 1.
    None if there is a matching dimension problem.
    Raises:
    This function should not raise any Exception.
    """
    theta = theta.astype(np.float64)
    for i in range(max_iter):
        grad = simple_gradient(x, y, theta)
        theta -= grad.astype(np.float64) * alpha
    return theta

In [ ]:
x = np.array([[12.4956442], [21.5007972], [31.5527382], [48.9145838], [57.5088733]])
y = np.array([[37.4013816], [36.1473236], [45.7655287], [46.6793434], [59.5585554]])
theta = np.array([1, 1]).reshape((-1, 1))
# Example 0:
theta1 = fit_(x, y, theta, alpha=5e-8, max_iter=1500000)
theta1 # Output: array([[1.40709365], [1.1150909 ]])

array([[1.40709365],
       [1.1150909 ]])

In [ ]:
# Example 1:
predict_(x, theta1)
# Output: array([[15.3408728 ], [25.38243697], [36.59126492],[65.53471499]])

array([[15.3408728 ],
       [25.38243697],
       [36.59126492],
       [55.95130097],
       [65.53471499]])

# Exercise 03

In [ ]:
class MyLinearRegression():
    """
    Description:
    My personnal linear regression class to fit like a boss.
    """
    def __init__(self, thetas, alpha=0.001, max_iter=1000):
        self.alpha = alpha
        self.max_iter = max_iter
        self.thetas = thetas

    def fit_(self, x, y):
        self.thetas = theta.astype(np.float64)
        for i in range(self.max_iter):
            grad = simple_gradient(x, y, self.thetas)
            self.thetas-= grad.astype(np.float64) * self.alpha
        return self.thetas

    def add_intercept(self, x):
        """
        Adds a column of 1’s to the non-empty numpy.array x.
        
        Args:
        x: has to be a numpy.array of dimension m * n.
        
        Returns:
        X, a numpy.array of dimension m * (n + 1).
        None if x is not a numpy.array.
        None if x is an empty numpy.array.
        
        Raises:
        This function should not raise any Exception.
        """
    
        if not isinstance(x, np.ndarray) or x.size == 0:
            return None
    
        if len(x.shape) == 1: x = x.reshape(x.shape[0], 1)
        
        ones = np.ones((x.shape[0], 1))
        X = np.hstack((ones, x))
        return X
    
    def predict_(self, x):
        """
        Computes the vector of prediction y_hat from two non-empty numpy.array.
        
        Args:
        x: has to be an numpy.array, a vector of dimension m * 1.
        theta: has to be an numpy.array, a vector of dimension 2 * 1.
        
        Returns:
        y_hat as a numpy.array, a vector of dimension m * 1.
        None if x and/or theta are not numpy.array.
        None if x or theta are empty numpy.array.
        None if x or theta dimensions are not appropriate.
        
        Raises:
        This function should not raise any Exceptions.
        """
    
        if not (isinstance(x, np.ndarray) and isinstance(self.thetas, np.ndarray)):
            return None
    
        if x.size == 0 or self.thetas.size == 0:
            return None
    
        if self.thetas.shape != (2,1):
             return None

        return self.add_intercept(x) @ self.thetas

    
    def loss_elem_(self, y, y_hat):
        if not (isinstance(y, np.ndarray) and isinstance(y_hat, np.ndarray)):
            return None
        
        if y.shape != y_hat.shape:
            return None
    
        J_elem = np.zeros(y.shape)
        for i in range(len(y)):
            J_elem[i] = (y[i] - y_hat[i]) ** 2

        return J_elem
        
    def loss_(self, y, y_hat):
        
        J_elem = self.loss_elem_(y, y_hat)
        if J_elem is None:
            return None
    
        J_value = 0.0
        for elem in J_elem:
            J_value += elem
        J_value /= (2 * len(J_elem))
    
        return float(J_value)

    @staticmethod
    def mse_(y, y_hat):
        """
        Description:
        Calculate the MSE between the predicted output and the real output.
        
        Args:
        y: has to be a numpy.array, a vector of dimension m * 1.
        y_hat: has to be a numpy.array, a vector of dimension m * 1.
        
        Returns:
        mse: has to be a float.
        None if there is a matching dimension problem.
        
        Raises:
        This function should not raise any Exceptions.
        """
        return ((y - y_hat) ** 2).mean()

    @classmethod
    def rmse_(y, y_hat):
        """
        Description:
        Calculate the RMSE between the predicted output and the real output.
        Args:
        y: has to be a numpy.array, a vector of dimension m * 1.
        y_hat: has to be a numpy.array, a vector of dimension m * 1.
        Returns:
        rmse: has to be a float.
        None if there is a matching dimension problem.
        Raises:
        This function should not raise any Exceptions.
        """
        return sqrt(mse_(y, y_hat))
    
    @classmethod
    def mae_(y, y_hat):
        """
        Description:
        Calculate the MAE between the predicted output and the real output.
        Args:
        y: has to be a numpy.array, a vector of dimension m * 1.
        y_hat: has to be a numpy.array, a vector of dimension m * 1.
        Returns:
        mae: has to be a float.
        None if there is a matching dimension problem.
        Raises:
        This function should not raise any Exceptions.
        """
        return np.abs(y - y_hat).mean()

    @classmethod
    def r2score_(y, y_hat):
        """
        Description:
        Calculate the R2score between the predicted output and the output.
        Args:
        y: has to be a numpy.array, a vector of dimension m * 1.
        y_hat: has to be a numpy.array, a vector of dimension m * 1.
        Returns:
        r2score: has to be a float.
        None if there is a matching dimension problem.
        Raises:
        This function should not raise any Exceptions.
        """
        return 1 - (((y - y_hat) ** 2).sum() / ((y - y.mean()) ** 2).sum())

In [ ]:
import numpy as np
x = np.array([[12.4956442], [21.5007972], [31.5527382], [48.9145838], [57.5088733]])
y = np.array([[37.4013816], [36.1473236], [45.7655287], [46.6793434], [59.5585554]])

lr1 = MyLinearRegression(np.array([[2], [0.7]]))
# Example 0.0:
y_hat = lr1.predict_(x)
y_hat
# Output: array([[10.74695094], [17.05055804], [24.08691674], [36.24020866], [42.25621131]])

array([[10.74695094],
       [17.05055804],
       [24.08691674],
       [36.24020866],
       [42.25621131]])

In [ ]:
# Example 0.1:
lr1.loss_elem_(y, y_hat)
# Output: array([[710.45867381], [364.68645485], [469.96221651], [108.97553412], [299.37111101]])

array([[710.45867381],
       [364.68645485],
       [469.96221651],
       [108.97553412],
       [299.37111101]])

In [ ]:
# Example 0.2:
lr1.loss_(y, y_hat)
# Output: 195.34539903032385

195.34539903032382

In [ ]:
# Example 1.0:
lr2 = MyLinearRegression(np.array([[1], [1]]), 5e-8, 1500000)
lr2.fit_(x, y)
lr2.thetas
# Output: array([[1.40709365], [1.1150909 ]])

array([[1.40709365],
       [1.1150909 ]])

In [ ]:
# Example 1.1:
y_hat = lr2.predict_(x)
y_hat
# Output: array([[15.3408728 ], [25.38243697], [36.59126492], [55.95130097], [65.53471499]])

array([[15.3408728 ],
       [25.38243697],
       [36.59126492],
       [55.95130097],
       [65.53471499]])

In [ ]:
# Example 1.2:
lr2.loss_elem_(y, y_hat)
# Output: array([[486.66604863], [115.88278416],[ 84.16711596], [ 85.96919719], [ 35.71448348]])

array([[486.66604863],
       [115.88278416],
       [ 84.16711596],
       [ 85.96919719],
       [ 35.71448348]])

In [ ]:
# Example 1.3:
lr2.loss_(y, y_hat)
# Output:80.8399629412852

80.83996294128524

# Exercise 04

In [ ]:
!ls .

are_blue_pills_magics.csv module_01-Copy1.ipynb     module_02.ipynb


In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
# from mylinearregression import MyLinearRegression as MyLR
data = pd.read_csv("./are_blue_pills_magics.csv")
Xpill = np.array(data['Micrograms']).reshape(-1,1)
Yscore = np.array(data['Score']).reshape(-1,1)
linear_model1 = MyLinearRegression(np.array([[89.0], [-8]]))
linear_model2 = MyLinearRegression(np.array([[89.0], [-6]]))
Y_model1 = linear_model1.predict_(Xpill)
Y_model2 = linear_model2.predict_(Xpill)
print(MyLinearRegression.mse_(Yscore, Y_model1))
# 57.60304285714282
print(mean_squared_error(Yscore, Y_model1))
# 57.603042857142825
print(MyLinearRegression.mse_(Yscore, Y_model2))
# 232.16344285714285
print(mean_squared_error(Yscore, Y_model2))
# 232.16344285714285

57.603042857142825
57.603042857142825
232.16344285714283
232.16344285714283


# Exercise 05

In [ ]:
def zscore(x):
    """
    Computes the normalized version of a non-empty numpy.ndarray using the z-score standardization.
    
    Args:
    x: has to be an numpy.ndarray, a vector.
    
    Returns:
    x’ as a numpy.ndarray.
    None if x is a non-empty numpy.ndarray or not a numpy.ndarray.
    
    Raises:
    This function shouldn’t raise any Exception.
    """
    mean, std = x.mean(), x.std()

    return (x - mean) / std

In [ ]:
# Example 1:
X = np.array([0, 15, -9, 7, 12, 3, -21])
zscore(X)
# Output: array([-0.08620324, 1.2068453 , -0.86203236, 0.51721942, 0.94823559, 0.17240647, -1.89647119])

array([-0.08620324,  1.2068453 , -0.86203236,  0.51721942,  0.94823559,
        0.17240647, -1.89647119])

In [ ]:
# Example 2:
Y = np.array([2, 14, -13, 5, 12, 4, -19]).reshape((-1, 1))
zscore(Y)
# Output: array([ 0.11267619, 1.16432067, -1.20187941, 0.37558731, 0.98904659, 0.28795027, -1.72770165])

array([[ 0.11267619],
       [ 1.16432067],
       [-1.20187941],
       [ 0.37558731],
       [ 0.98904659],
       [ 0.28795027],
       [-1.72770165]])

# Exercise 06

In [ ]:
def minmax(x):
    """Computes the normalized version of a non-empty numpy.ndarray using the min-max standardization.
    Args:
    x: has to be an numpy.ndarray, a vector.
    Returns:
    x’ as a numpy.ndarray.
    None if x is a non-empty numpy.ndarray or not a numpy.ndarray.
    Raises:
    This function shouldn’t raise any Exception.
    """
    min, max = x.min(), x.max()
    return (x - min) / (max - min)

In [ ]:
# Example 1:
X = np.array([0, 15, -9, 7, 12, 3, -21]).reshape((-1, 1))
minmax(X)
# Output: array([0.58333333, 1. , 0.33333333, 0.77777778, 0.91666667,0.66666667, 0. ])

array([[0.58333333],
       [1.        ],
       [0.33333333],
       [0.77777778],
       [0.91666667],
       [0.66666667],
       [0.        ]])

In [ ]:
# Example 2:
Y = np.array([2, 14, -13, 5, 12, 4, -19]).reshape((-1, 1))
minmax(Y)
# Output: array([0.63636364, 1. , 0.18181818, 0.72727273, 0.93939394, 0.6969697 , 0. ])

array([[0.63636364],
       [1.        ],
       [0.18181818],
       [0.72727273],
       [0.93939394],
       [0.6969697 ],
       [0.        ]])